<!DOCTYPE html>
<html lang="en">

<!-- header section -->
<?php include '../js/header.php';?>

<body>


	<div class="container text-center rounded_rectangle" style="margin-top:60px">
		<div class="row" style="padding:15px">
			<!-- <div class="col-md-12 col-sm-12"> -->
			<div class="hero-unit">
				<h1><span> An automated building thermal model generator and HVAC control performance simulation tool</span></h1>
			</div>
			<!-- </div> -->
		</div>
		<div class="row" style="padding:15px">
			<img class="one" src="./images/toolflow.jpeg" width="700" height="400" alt="HVAC">
		</div>
		<div class="row topic-desc" style="padding:15px">
			<p><span>

				Note: The tool is in developing phase and constantly updated for in house experiments. The latest version of the tool will be available on request(mailto:rajib.jana@cse.iitkgp.ernet.in, cc:jlrajib.cse@gmail.com). In order to get the flavour of allocation-aware HVAC control synthesis, reader can download the <a href="./images/tarball.zip" download ="tarball.zip">tarball</a> which contains final output files generated by the tool for given inputs. The output file (simulation.py) is required to execute for analyzing the HVAC performance. The necessary information to execute the file is mentioned in <a href="./images/readme.pdf" download ="readme.pdf">readMe file</a>.
				</span></p>
		</div>
		<br>
			<hr class="divider-line">
						<div class="row">
				<div class="col-md-5 col-sm-5"></div>
				<div class="col-md-2 col-sm-2" style="padding:20px">
				<a href="./index_grid.php#SmartGridresearch" class="btn btn-default" style="border-color:#885104;border-style:solid">Back To Smart Grid</a>
				</div>
				<div class="col-md-5 col-sm-5"></div>
			</div>
	</div>						
								

<!-- footer section -->
<?php include '../footer.php';?>

</body>
</html>
